name: Deploy WebApi

env:
  AZURE_WEBAPP_NAME: backend-realestate # set this to your application's name

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - "webApi/**" # Only trigger on changes in the frontend folder
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - "webApi/**" # Only trigger on changes in the frontend folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Install dependencies
        run: dotnet restore ./webApi/webApi.csproj

      - name: Build with dotnet
        run: dotnet build ./webApi/webApi.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet build ./webApi/webApi.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ./publish
